# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HexToZoneEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexToZoneEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexToZoneEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexToZoneEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexToZoneEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HexToZoneEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def HexToZoneEntryStart(builder):
    builder.StartObject(2)

def Start(builder):
    HexToZoneEntryStart(builder)

def HexToZoneEntryAddHexId(builder, hexId):
    builder.PrependUint64Slot(0, hexId, 0)

def AddHexId(builder, hexId):
    HexToZoneEntryAddHexId(builder, hexId)

def HexToZoneEntryAddZoneId(builder, zoneId):
    builder.PrependUint16Slot(1, zoneId, 0)

def AddZoneId(builder, zoneId):
    HexToZoneEntryAddZoneId(builder, zoneId)

def HexToZoneEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return HexToZoneEntryEnd(builder)
