# automatically generated by the FlatBuffers compiler, do not modify

# namespace: timezonefinder.flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HexUniqueZoneEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexUniqueZoneEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexUniqueZoneEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexUniqueZoneEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexUniqueZoneEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HexUniqueZoneEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def HexUniqueZoneEntryStart(builder):
    builder.StartObject(2)

def Start(builder):
    HexUniqueZoneEntryStart(builder)

def HexUniqueZoneEntryAddHexId(builder, hexId):
    builder.PrependUint64Slot(0, hexId, 0)

def AddHexId(builder, hexId):
    HexUniqueZoneEntryAddHexId(builder, hexId)

def HexUniqueZoneEntryAddZoneId(builder, zoneId):
    builder.PrependUint16Slot(1, zoneId, 0)

def AddZoneId(builder, zoneId):
    HexUniqueZoneEntryAddZoneId(builder, zoneId)

def HexUniqueZoneEntryEnd(builder):
    return builder.EndObject()

def End(builder):
    return HexUniqueZoneEntryEnd(builder)