# automatically generated by the FlatBuffers compiler, do not modify

# namespace: timezonefinder.flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

from timezonefinder.flatbuf.HexUniqueZoneEntry import HexUniqueZoneEntry
class HexUniqueZoneCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexUniqueZoneCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexUniqueZoneCollection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexUniqueZoneCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexUniqueZoneCollection
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = HexUniqueZoneEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HexUniqueZoneCollection
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HexUniqueZoneCollection
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HexUniqueZoneCollectionStart(builder):
    builder.StartObject(1)

def Start(builder):
    HexUniqueZoneCollectionStart(builder)

def HexUniqueZoneCollectionAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

def AddEntries(builder, entries):
    HexUniqueZoneCollectionAddEntries(builder, entries)

def HexUniqueZoneCollectionStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartEntriesVector(builder, numElems):
    return HexUniqueZoneCollectionStartEntriesVector(builder, numElems)

def HexUniqueZoneCollectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return HexUniqueZoneCollectionEnd(builder)