# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

from timezonefinder.flatbuf.HexZoneMappingEntry import HexZoneMappingEntry

class HexZoneMappingCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexZoneMappingCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexZoneMappingCollection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexZoneMappingCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexZoneMappingCollection
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = HexZoneMappingEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HexZoneMappingCollection
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HexZoneMappingCollection
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def Start(builder): builder.StartObject(1)
def HexZoneMappingCollectionStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddEntries(builder, entries): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)
def HexZoneMappingCollectionAddEntries(builder, entries):
    """This method is deprecated. Please switch to AddEntries."""
    return AddEntries(builder, entries)
def StartEntriesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def HexZoneMappingCollectionStartEntriesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartEntriesVector(builder, numElems)
def End(builder): return builder.EndObject()
def HexZoneMappingCollectionEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)