# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HexZoneEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexZoneEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexZoneEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexZoneEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexZoneEntry
    def H3Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HexZoneEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def HexZoneEntryStart(builder): builder.StartObject(2)
def Start(builder):
    return HexZoneEntryStart(builder)
def HexZoneEntryAddH3Id(builder, h3Id): builder.PrependUint64Slot(0, h3Id, 0)
def AddH3Id(builder, h3Id):
    return HexZoneEntryAddH3Id(builder, h3Id)
def HexZoneEntryAddZoneId(builder, zoneId): builder.PrependInt32Slot(1, zoneId, 0)
def AddZoneId(builder, zoneId):
    return HexZoneEntryAddZoneId(builder, zoneId)
def HexZoneEntryEnd(builder): return builder.EndObject()
def End(builder):
    return HexZoneEntryEnd(builder)