# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HexZoneMappingEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HexZoneMappingEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHexZoneMappingEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HexZoneMappingEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HexZoneMappingEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HexZoneMappingEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(2)
def HexZoneMappingEntryStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddHexId(builder, hexId): builder.PrependUint64Slot(0, hexId, 0)
def HexZoneMappingEntryAddHexId(builder, hexId):
    """This method is deprecated. Please switch to AddHexId."""
    return AddHexId(builder, hexId)
def AddZoneId(builder, zoneId): builder.PrependUint16Slot(1, zoneId, 0)
def HexZoneMappingEntryAddZoneId(builder, zoneId):
    """This method is deprecated. Please switch to AddZoneId."""
    return AddZoneId(builder, zoneId)
def End(builder): return builder.EndObject()
def HexZoneMappingEntryEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)