# automatically generated by the FlatBuffers compiler, do not modify

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UniqueZoneEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUniqueZoneEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UniqueZoneEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniqueZoneEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # UniqueZoneEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def UniqueZoneEntryStart(builder): builder.StartObject(2)
def Start(builder):
    return UniqueZoneEntryStart(builder)
def UniqueZoneEntryAddHexId(builder, hexId): builder.PrependUint64Slot(0, hexId, 0)
def AddHexId(builder, hexId):
    return UniqueZoneEntryAddHexId(builder, hexId)
def UniqueZoneEntryAddZoneId(builder, zoneId): builder.PrependUint16Slot(1, zoneId, 0)
def AddZoneId(builder, zoneId):
    return UniqueZoneEntryAddZoneId(builder, zoneId)
def UniqueZoneEntryEnd(builder): return builder.EndObject()
def End(builder):
    return UniqueZoneEntryEnd(builder)
