# automatically generated by the FlatBuffers compiler, do not modify

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UniqueZoneEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniqueZoneEntry(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def UniqueZoneEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHas
    
    # UniqueZoneEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniqueZoneEntry
    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # UniqueZoneEntry
    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def UniqueZoneEntryStart(builder):
    builder.StartObject(2)

def UniqueZoneEntryAddHexId(builder, hexId):
    builder.PrependUint64Slot(0, hexId, 0)

def UniqueZoneEntryAddZoneId(builder, zoneId):
    builder.PrependUint16Slot(1, zoneId, 0)

def UniqueZoneEntryEnd(builder):
    return builder.EndObject()
