# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UniqueZoneShortcutEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniqueZoneShortcutEntry(cls, buf, offset):
        n = flatbuffers.encode.Get(buf, offset)
        x = UniqueZoneShortcutEntry()
        x.Init(buf, n)
        return x

    @classmethod
    def UniqueZoneShortcutEntryBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b'\x46\x42\x53\x31', size_prefixed=size_prefixed)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    def HexId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    def ZoneId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def UniqueZoneShortcutEntryStart(builder):
    builder.StartObject(2)

def UniqueZoneShortcutEntryAddHexId(builder, hexId):
    builder.PrependUint64Slot(0, hexId, 0)

def UniqueZoneShortcutEntryAddZoneId(builder, zoneId):
    builder.PrependUint16Slot(1, zoneId, 0)

def UniqueZoneShortcutEntryEnd(builder):
    return builder.EndObject()
