# UniqueZoneCollection
# Generated by flatc compiler (version 24.3.25).
#
# Do not modify this file manually.

# namespace timezonefinder.flatbuf;

import flatbuffers
from flatbuffers.compat import import_numpy

np = import_numpy()


class UniqueZoneCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniqueZoneCollection(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def UniqueZoneCollectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        # Using a custom identifier for UniqueZoneCollection (e.g., UZCO)
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b'\x55\x5A\x43\x4F', size_prefixed=size_prefixed)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from timezonefinder.flatbuf.UniqueZoneEntry import UniqueZoneEntry
            obj = UniqueZoneEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    @classmethod
    def Start(cls, builder):
        builder.StartObject(1)

    @classmethod
    def AddEntries(cls, builder, entries):
        builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

    @classmethod
    def StartEntriesVector(cls, builder, numElems):
        return builder.StartVector(4, numElems, 4)

    @classmethod
    def End(cls, builder):
        return builder.EndObject()
