# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UniqueZoneShortcutCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniqueZoneShortcutCollection(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneShortcutCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def UniqueZoneShortcutCollectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b'\x44\x42\x46\x54', size_prefixed=size_prefixed)

    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from timezonefinder.flatbuf.UniqueZoneShortcutEntry import UniqueZoneShortcutEntry
            obj = UniqueZoneShortcutEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def UniqueZoneShortcutCollectionStart(builder):
    builder.StartObject(1)

def UniqueZoneShortcutCollectionAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

def UniqueZoneShortcutCollectionStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def UniqueZoneShortcutCollectionEnd(builder):
    return builder.EndObject()
