# automatically generated by the FlatBuffers compiler, do not modify

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

from timezonefinder.flatbuf.UniqueZoneEntry import UniqueZoneEntry

class UniqueZoneCollection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsUniqueZoneCollection(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def UniqueZoneCollectionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b'\x46\x42\x43\x53', size_prefixed=size_prefixed)

    # UniqueZoneCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniqueZoneCollection
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = UniqueZoneEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UniqueZoneCollection
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def UniqueZoneCollectionStart(builder):
    builder.StartObject(1)

def UniqueZoneCollectionAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

def UniqueZoneCollectionStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def UniqueZoneCollectionEnd(builder):
    return builder.EndObject()
