# automatically generated by the FlatBuffers compiler, do not modify
# namespace: timezonefinder.flatbuf

import flatbuffers
from flatbuffers.compat import import_numpy

from timezonefinder.flatbuf.UniqueZoneEntry import UniqueZoneEntry

np = import_numpy()


class UniqueZoneCollection(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UniqueZoneCollection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUniqueZoneCollection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)

    # UniqueZoneCollection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UniqueZoneCollection
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = UniqueZoneEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UniqueZoneCollection
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UniqueZoneCollection
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0


def Start(builder):
    builder.StartObject(1)


def UniqueZoneCollectionStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)


def AddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0
    )


def UniqueZoneCollectionAddEntries(builder, entries):
    """This method is deprecated. please switch to AddEntries."""
    return AddEntries(builder, entries)


def StartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def UniqueZoneCollectionStartEntriesVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartEntriesVector(builder, numElems)


def End(builder):
    return builder.EndObject()


def UniqueZoneCollectionEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)
